---
abstract: 'a perl content_filter for postfix'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Postfix-ContentFilter
no_index:
  directory:
    - t
    - inc
requires:
  IPC::Open3: 1.12
  Test::More: 0
  Try::Tiny: 0.11
version: 1.10
